version: "3"

services:
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
  postgres:
    image: postgres:latest
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./postgres:/var/lib/postgresql/data 
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - postgres
  server:
    image: node:19.0.0-alpine
    working_dir: /home/node
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run start:dev"
    environment:
      - MONGO_URL=mongodb://db:27017/my-nest-db?authSource=admin
    volumes:
      - ./server:/home/node
    depends_on:
      - db
      - postgres

  client:
    image: node:19.0.0-alpine
    working_dir: /home/node
    ports:
      - 8000:8000
    volumes:
      - ./client:/home/node
    command: sh -c "npm install && npm run development"
    environment:
      - REACT_API_URL=http://localhost:3000
      - CLIENT_PORT=3001
      - CLIENT_HOST=0.0.0.0

  kpi_front:
    image: node:19.0.0-alpine
    working_dir: /home/node
    stdin_open: true
    ports:
      - 8001:8001
    volumes:
      - ./kpi_front:/home/node
    command: sh -c "npm install && npm run start"
    environment:
      - REACT_API_URL=http://localhost:3000
      - CLIENT_PORT=3001
      - CLIENT_HOST=
      
volumes:
  db: {}
