apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpi-server
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: kpi-server
  template:
    metadata:
      labels:
        app: kpi-server
    spec:
      containers:
      - name: kpi-server
        image: yacinesoussi/kpi-server:latest
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_HOST
          value: "kpi-server-postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_POSTGRES_DB
        - name: MONGO_URL
          value: "mongodb://kpi-server-mongo:27018/kpi"



---

apiVersion: v1
kind: Service
metadata:
  name: kpi-server-external
  labels:
    app: kpi-server
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: kpi-server

--- 

apiVersion: v1
kind: Service
metadata:
  name: kpi-server-internal
  labels:
    app: kpi-server
spec: 
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: kpi-server

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kpi-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kpi-server
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50


