name: Publish Docker image

on:
  push:
    branches:
      - main
env:
  GKE_CLUSTER: marketplace
  GKE_ZONE: europe-west1

jobs:

  publish-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push challenge-front
        uses: docker/build-push-action@v2
        with:
          context: ./kpi_front
          file: ./kpi_front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kpi-front:latest
      
      - name: Build and push challenge-users
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kpi-server:latest
          
  deploy-kubernetes:
    runs-on: ubuntu-latest
    needs: publish-docker
    steps:
      - name: Set up Kubernetes
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Deploy kpi-front
        run: |
          kubectl patch deployment kpi-front -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"

      - name: Deploy kpi-server
        run: |
          kubectl patch deployment kpi-server -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"